{
 "title": "NGINX exporter",
 "description": "Official dashboard for NGINX Prometheus exporter for https://github.com/nginxinc/nginx-prometheus-exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$instance*\",cpu=\"cpu-total\"})",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Current CPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$instance*\",cpu=\"cpu-total\"})",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mem_used{instance=~\"$instance\"})",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "rate(net_bytes_recv[5m])", "legendFormat": "net_bytes_recv" },
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "rate(net_bytes_sent[5m])", "legendFormat": "net_bytes_sent" },
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  },
  { "title": "Nginx Requests Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Response 2XX / 5m",
   "type": "graph",
   "description": "Requests with 200 Status Code",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"20.\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Response 200 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 200 response by nginx server",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"200\"}[24h])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Response 4XX /5m",
   "type": "graph",
   "description": "Requests with 4XX Status Code",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"40.\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Response 404 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 404 response from nginx server",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"404\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Response 3XX",
   "type": "graph",
   "description": "Requests with 3XX Status Code",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"30.\"}[5m])",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Response 5XX",
   "type": "graph",
   "description": "Requests with 5XX Status Code",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"50.\"}[5m])",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request 503 Response",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(nginxlog_resp_bytes{instance=~\"$instance*\", resp_code=~\"503\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  { "title": "Nginx Metrics (Additional)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Nginx Connections Accepted",
   "type": "graph",
   "description": "The total number of accepted connections from clients since the nginx master process started.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_accepted{instance=~\"$instance*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Writing",
   "type": "stat",
   "description": "The current number of connections from clients where nginx is writing a response back to the client.",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance*\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Nginx Active Connections[accepted]",
   "type": "bargauge",
   "description": "The current number of active (accepted) connections from clients.",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance*\"}",
     "legendFormat": "{{instance }}"
    }
   ]
  },
  {
   "title": "Nginx Waiting Connections",
   "type": "stat",
   "description": "The current number of connections from clients that are in the Idle / Waiting state.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance*\"}",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Handled Request",
   "type": "graph",
   "description": "The total number of handled connections from clients since the nginx master process started.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_handled{instance=~\"$instance*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nginx Requests",
   "type": "graph",
   "description": "The total number of client requests since the nginx master process started.",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_requests_total{instance=~\"$instance*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "nginx_reading",
   "type": "stat",
   "description": "The current number of (accepted) connections from clients where nginx is reading the request.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance*\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Each Request Detail",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "nginxlog_resp_bytes{instance=~\"$instance*\"}"
    }
   ]
  },
  {
   "title": "Request Distribution by Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 }
  },
  {
   "title": "App Service - Request Distribution by Pods (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"app-service\"}[5m])) by (pod, instance) / sum(rate(ktor_http_server_requests_seconds_count{job=\"app-service\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "User Service - Request Distribution by Pods (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"user-service\"}[5m])) by (pod, instance) / sum(rate(ktor_http_server_requests_seconds_count{job=\"user-service\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Auth Service - Request Distribution by Pods (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"authservice\"}[5m]) or rate(ktor_http_server_requests_seconds_count{job=\"authservice\"}[5m])) by (pod, instance) / sum(rate(http_requests_received_total{job=\"authservice\"}[5m]) or rate(ktor_http_server_requests_seconds_count{job=\"authservice\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Prolog Service - Request Distribution by Pods (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=~\"prolog.*\"}[5m]) or rate(http_requests_total{job=~\"prolog.*\"}[5m])) by (pod, instance) / sum(rate(ktor_http_server_requests_seconds_count{job=~\"prolog.*\"}[5m]) or rate(http_requests_total{job=~\"prolog.*\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "App Service - Request Distribution (%)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"app-service\"}[5m])) by (pod, instance) / sum(rate(ktor_http_server_requests_seconds_count{job=\"app-service\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "User Service - Request Distribution (%)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"user-service\"}[5m])) by (pod, instance) / sum(rate(ktor_http_server_requests_seconds_count{job=\"user-service\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Auth Service - Request Distribution (%)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"authservice\"}[5m]) or rate(ktor_http_server_requests_seconds_count{job=\"authservice\"}[5m])) by (pod, instance) / sum(rate(http_requests_received_total{job=\"authservice\"}[5m]) or rate(ktor_http_server_requests_seconds_count{job=\"authservice\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Prolog Service - Request Distribution (%)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=~\"prolog.*\"}[5m]) or rate(http_requests_total{job=~\"prolog.*\"}[5m])) by (pod, instance) / sum(rate(ktor_http_server_requests_seconds_count{job=~\"prolog.*\"}[5m]) or rate(http_requests_total{job=~\"prolog.*\"}[5m]))",
     "legendFormat": "{{pod}}{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Request Distribution by Service (%)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"app-service\"}[5m]))",
     "legendFormat": "App Service"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"user-service\"}[5m]))",
     "legendFormat": "User Service"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=\"authservice\"}[5m]))",
     "legendFormat": "Auth Service"
    },
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{job=~\"prolog.*\"}[5m]))",
     "legendFormat": "Prolog Service"
    }
   ]
  }
 ]
}