apiVersion: v1
kind: Service
metadata:
  name: servers-app-2
  namespace: microservices-lab
spec:
  selector:
    app: servers-app-1
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP


