@startuml c4-container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

title Диаграмма контейнеров (C4 Container) - Сервис кино

Person(user, "Пользователь", "Обычный пользователь системы")
Person(admin, "Администратор", "Администратор системы")
Person(moderator, "Модератор", "Пользоветль с правами модератора")

System_Boundary(movie_system, "Сервис кино") {
    Container(backend, "Backend", "Микросервисная архитектура", "Набор микросервисов для обработки бизнес-логики")
    ContainerDb(database, "База данных", "MongoDB", "Хранит информацию о фильмах, пользователях, сессиях")
    ContainerDb(redis, "Кэш", "Redis", "Кэширование данных, сессии пользователей")
    Container(kafka, "Брокер сообщений", "Kafka + Zookeeper", "Асинхронная обработка событий между микросервисами")
}

System_Ext(video_hosting, "Хостинг видео", "Внешний сервис хранения видео")

Rel(user, backend, "Использует", "HTTPS/REST API")
Rel(admin, backend, "Управляет", "HTTPS/REST API")
Rel(moderator, backend, "Использует", "HTTPS/REST API")

Rel(backend, database, "Читает/записывает данные", "MongoDB Protocol")
Rel(backend, redis, "Кэширует данные, управляет сессиями", "Redis Protocol")
Rel(backend, kafka, "Публикует/подписывается на события", "Kafka Protocol")
Rel(backend, video_hosting, "Получает видео контент", "HTTPS/API")

@enduml

