@startuml C4 Context Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Диаграмма контекста - Сервис кино

Person(user, "Пользователь", "Использует сервис для просмотра фильмов и получения рекомендаций")
Person(admin, "Администратор", "Управляет контентом и пользователями системы")
Person(moderator, "Модератор", "Добавляет контент и согласует изменения от пользователей")

System(cinema_service, "Сервис кино", "Микросервисная платформа для управления фильмами, пользователями и рекомендациями")

System_Ext(video_hosting, "Хостинг видео", "Внешний сервис для хранения и доставки видео контента")
Rel(moderator, cinema_service, "Добавляет контент и согласует изменения от пользователей")

Rel(user, cinema_service, "Просматривает фильмы, получает рекомендации" )
Rel(admin, cinema_service, "Управляет контентом и пользователями" )
Rel(cinema_service, video_hosting, "Получает видео контент" )

@enduml

